name: snowpark-de-ml
channels:
  - https://repo.anaconda.com/pkgs/snowflake
dependencies:
  - python=3.9
  - snowflake-snowpark-python=1.4.0
  - pandas=1.5.3
  - notebook=6.5.4
  - scikit-learn=1.2.2
  - cachetools=4.2.2
  - boto3
  - pip
  - pip:
    - streamlit==1.23.1
    - snowflake-ml-python==1.0.0
 
